version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: el-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database/data:/var/lib/mysql
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: el-elastic
    ports:
      - 9200:9200
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  logstash:
    build: ./logstash
    container_name: logstash
    volumes:
      - ./logstash/conf/:/usr/share/logstash/pipeline/
      - ./logstash/java/:/home/java/
    depends_on:
      - mysql
      - elastic
